name: Run Cosmonaut on macOS

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run binary
        run: |
          chmod +x cosmonaut.com
          ./cosmonaut.com || true
